version: '3.2'
services:
  kibana:
    depends_on:
      - elasticsearch
     # - es02
      - logstash
    image: docker.elastic.co/kibana/kibana:7.3.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    restart: unless-stopped


  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.1
    container_name: logstash
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
      XPACK_MONITORING_ELASTICSEARCH_URLS: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "false"
    volumes:
      - ./:/usr/share/logstash/pipeline:ro
    restart: unless-stopped
    depends_on:
      - elasticsearch
     # - es02

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      #- discovery.seed_hosts=es02
      - cluster.initial_master_nodes=elasticsearch #,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

#  es02:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
#    container_name: es02
#    environment:
#      - node.name=es02
#      - discovery.seed_hosts=elasticsearch
#      - cluster.initial_master_nodes=elasticsearch,es02
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata02:/usr/share/elasticsearch/data
#    healthcheck:
#      test: "wget -q -O - http://localhost:9200/_cat/health"
#      interval: 1s
#      timeout: 30s
#      retries: 300
#    restart: unless-stopped
volumes:
  esdata01:
    driver: local
#  esdata02:
#    driver: local